In [3]:
# NumPy stands for Numeric Python 
# - a python library
# - used for working with arrays
# - 50X faster than list
# - takes up continous memory
# - supports vectorization


In [5]:
import numpy as np
np.__version__

'2.0.2'

In [6]:
my_np_array = np.array(
    [1,2,3]
)
print(my_np_array)
print(type(my_np_array))

# Property 1: datatype
print(my_np_array.dtype)

# Property 2: shape
print(my_np_array.shape)

# Property 3: dimension
print(my_np_array.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [7]:
# Creating an array with all zeros
zeros_np_array = np.zeros(
    shape=(5,)
)
zeros_np_array

array([0., 0., 0., 0., 0.])

In [8]:
# Creating an array with all ones
ones_np_array = np.ones(
    shape=(5,)
)
ones_np_array

array([1., 1., 1., 1., 1.])

In [9]:
# Creating an array with all ones integer type
ones_np_array = np.ones(
    shape=(10, 2),
    dtype = 'int'
)
print(ones_np_array)
print(ones_np_array.dtype)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
int64


In [10]:
# Creating an array with a specific value
assigned_with_specific_np_array = np.full(
    shape =(10,),
    fill_value=15,
)
assigned_with_specific_np_array

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [11]:
# Creating Identitiy Matrix
id_matrix = np.eye(3)
id_matrix
#print(id_matrix)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Creating empty array
my_empty_np_array =np.empty(
    shape=(5,)
)
my_empty_np_array

array([1., 1., 1., 1., 1.])

In [13]:
# lsit to numpy
my_list = [1,2,3]
my_np_list = np.array(
    my_list
)
my_np_list

# Type Cast
print(my_np_list.dtype)
my_np_list_float = my_np_list.astype('float')
print(my_np_list_float.dtype)

int64
float64


In [14]:
# Creating sequential array
my_array = np.arange(start = 1, stop =10, step = 1) #start, end-1, increment(by deafult step=1)
my_array
my_array = np.arange(3,9) #start, end-1, increment(by deafult step=1)
my_array

array([3, 4, 5, 6, 7, 8])

In [15]:
my_np_array = np.linspace(
    start = 3,
    stop = 9,
    num = 3 # generate 3 number that are at equal distances
)
my_np_array
# linspace --> generates an array of evenly spaced numbers over a defined interval
my_np_array = np.linspace(
    start = 1,
    stop = 100,
    num = 10 
)
my_np_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
# Mathematical Objects | Dimension
# - Scalar --> 0D
# - Vector --> 1D
# - Matrix --> 2D
# - Tensor --> xD where x > 2 : a unit data type of PyTorch and Tensorflow

my_0d_array = np.array(9)
print('0-dimensional array ; ', my_0d_array, '\nndim:', my_0d_array.ndim)

my_1d_array = np.array(
    [1.5, 2, 3.3, 4.7, 5.1, 6]
)
print('1-dimensional array ; ', my_1d_array, '\nndim:', my_1d_array.ndim)

my_2d_array = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]   
)
print('2-dimensional array ; ', my_2d_array, '\nndim:', my_2d_array.ndim)


0-dimensional array ;  9 
ndim: 0
1-dimensional array ;  [1.5 2.  3.3 4.7 5.1 6. ] 
ndim: 1
2-dimensional array ;  [[1 2 3]
 [4 5 6]
 [7 8 9]] 
ndim: 2


In [17]:
# NumPy Indexing
my_np_array = np.array(
    [1, 2, 3, 4, 5]
)
print(my_np_array[2])
print(my_np_array[-2])

my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 6],
     [7, 1, 2, 7]]
)
print(my_2d_array[0])
print(my_2d_array[1,1])
print(my_2d_array[1,-1])

3
4
[1 2 3 4]
8
6


In [18]:
# NumPy Slicing : picking subarray 
my_np_array = np.array(
    [1, 2, 3, 4, 5, 7, 8]
)
my_np_array[1:3] # by default step count 1
my_np_array[1:4:1]
my_np_array[0:5:2]
my_np_array[:3] # index 0 to 2
my_np_array[::]


my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 6],
     [7, 1, 2, 7]]
)
my_2d_array[0:2, ]
my_2d_array[0:2, 1:3]
# my_2d_array[, 1:3] --> does not work

array([[2, 3],
       [8, 9]])

# A cell can be two types: code, markdown
# NumPy Array Iteration

In [21]:
import numpy as np
np_array = np.array(
    [1, 2, 3, 4, 5, 6]
)
print(np_array)

[1 2 3 4 5 6]


In [23]:
# Option 1: Iterate by value (accessing the values sequentially)

for val in np_array:
    print(val)

1
2
3
4
5
6


In [24]:
# Option 2: Iterate by index (accessing the values index number sequentially)

for i in range(len(np_array)):
    print (np_array[i])


1
2
3
4
5
6


In [25]:
# Option 2: Iterate by value and index (accessing both the values and index number sequentially)
for i, val in enumerate(np_array):
    print(f"index = {i} value = {val}")

index = 0 value = 1
index = 1 value = 2
index = 2 value = 3
index = 3 value = 4
index = 4 value = 5
index = 5 value = 6


# NumPy Methods

In [32]:
# Reshape 
# Purpose: reshaping matrices for multiplication operations, does not change elements of matrix
# Condition: multiplication of dimension values before and after reshaping must be ame
# Working Principle 
# Step 1: flattening --> 1D
# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
# Step 2: reshaping 
# [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]] 
my_2d_array = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12],
     [13, 14, 15]]
)
print(my_2d_array)
print(my_2d_array.shape)
print(my_2d_array.reshape(3, 5)) #converts to 3 rows, 5 columns
# print(my_2d_array.reshape(3, 4)) --> valueError: cannot reshape array of size 15 into shape (3,4)
print(my_2d_array.reshape(15, 1))
print(my_2d_array.reshape(1, 3, 5)) # turns into 3D matrix: 1 matrix has 3 elements, and each elements have 5 elements

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(5, 3)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [42]:
# Reshaping with -1 : to calculate the unknown dimension in reshape method
# size of my_np_array 3 * 4 * 2 * 2 = 48
my_np_array = np.zeros(shape=(3, 4, 2, 2))
print(my_np_array)
print(my_np_array.reshape(2, 2, 12))
my_np_array_reshaped = my_np_array.reshape(2, 2, -1)
print(my_np_array_reshaped)
print(my_np_array_reshaped.shape)
# print(my_np_array.reshape(-1, 2, -1)) --> ValueError: can only specify one unknown dimension

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(2, 2, 12)


In [45]:
# sort
probabilities = np.array(
    [0.3, 0.1, 0.4, 0.2]
)
probabilities_sorted = np.sort(probabilities)
print(probabilities_sorted)

probabilities_reverse_sort =  np.sort(probabilities)[::-1] #slicing technique
print(probabilities_reverse_sort)

[0.1 0.2 0.3 0.4]
[0.4 0.3 0.2 0.1]


In [48]:
# Argmax, Argmin: by using these we get the max value and min value for our model for predition
# prints max/min value contained index
index_max = np.argmax(probabilities)
print(index_max)

index_min = np.argmin(probabilities)
print(index_min)

2
1


In [52]:
# split: divides in equal portions
# split data to test model
my_np_array = np.array([1, 5, 1, 1, 5, 7])
new_np_array = np.split(
    my_np_array, 
    indices_or_sections=3 
)
print(new_np_array)

[array([1, 5]), array([1, 1]), array([5, 7])]


In [53]:
# Dot Product
# v1 = 3i + 2j
# v2 = 3i - 2j
# v1 . v2 = (3 * 3) + (2 * -2) = 5

my_np_array_1 = np.array(
    [3, 4, 5]
)

my_np_array_2 = np.array(
    [1, 2, 3]
)
print(my_np_array_1)
print(my_np_array_2)

dot_product = np.dot(my_np_array_1, my_np_array_2)
print(dot_product)


[3 4 5]
[1 2 3]
26


In [54]:
# matrix transpose

my_2d_array_1 = np.array (
    [[2, 1, 3],
    [7, 5, 6]]
)
print(my_2d_array_1)
print(my_2d_array_1.shape)
print(my_2d_array_1.T)
print(my_2d_array_1.T.shape)

[[2 1 3]
 [7 5 6]]
(2, 3)
[[2 7]
 [1 5]
 [3 6]]
(3, 2)


In [55]:
# statistical methods
my_np_array = np.array([1, 5, 1, 1, 5, 7])
print(np.mean(my_np_array))
print(np.median(my_np_array))
print(np.std(my_np_array))

3.3333333333333335
3.0
2.4267032964268394


# NumPy Filtering

In [56]:
# 1. Boolean Mask
my_1d_array = np.array(
    [ 1, 2, 3, 4, 5, 6]
)

filter_mask = [True, False, True, False, True, False]
filtered_array = my_1d_array[filter_mask]
print(filtered_array)

[1 3 5]


In [59]:
# 2. Conditional
filter_mask = (my_1d_array % 2 == 0)
print(filter_mask)
filtered_array = my_1d_array[filter_mask]
print(filtered_array)

[False  True False  True False  True]
[2 4 6]


In [60]:
# 3. Indices
indices =[0, 1, 5]
filtered_array = my_1d_array[indices]
print(filtered_array)

[1 2 6]


In [62]:
# Custom Filter Metod

def my_filter_method(x):
    if x % 2 == 1:
        return False
    return True

filtered_iterable = filter(my_filter_method, my_1d_array)
my_filtered_array = np.array(
    list(filtered_iterable)
)
my_filtered_array

array([2, 4, 6])

# Vectorization
# The process of performing operations on entire arrays (or vector) without the ned for explicit loops

In [63]:
# Does operation in one move
my_1d_array = np.array(
    [1, 2, 3, 4, 5, 6, 7, 9]
)
print(my_1d_array)
my_1d_array % 2 == 1

[1 2 3 4 5 6 7 9]


array([ True, False,  True, False,  True, False,  True,  True])

In [72]:
my_1d_array = np.array(
    [1, 2, 3, 4, 5, 6, 7, 9]
)
print(my_1d_array)

for x in my_1d_array:
    x = x + 5
print(my_1d_array)

my_1d_array = my_1d_array + 5 # vectorization --> faster
print(my_1d_array)

[1 2 3 4 5 6 7 9]
[1 2 3 4 5 6 7 9]
[ 6  7  8  9 10 11 12 14]


# Broadcasting
# Converting a lower shape into Higher shape for vectorization

In [77]:
# condition: Two dimensions must be Compatible (right-->left)
w = np.array(
    [1, 2]
)

x = np.array([
    [3, 4],
    [5, 6],
    [7, -8],
    [5, -3]
    ])

print(w * x)

[[  3   8]
 [  5  12]
 [  7 -16]
 [  5  -6]]
